### ISSUE TITLE
Elasticsearch 5.0

### ISSUE THREAD

**Issue by matthewdu** [omc/searchyll#17]
The api for `cat index` changed in ES 5.0. By default it no longer returns a json.

https://github.com/omc/searchyll/blob/master/lib/searchyll/indexer.rb#L136
The endpoint here needs to be changed to 
```
/_cat/indices?h=index&format=json
```

For reference:
https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html#_response_as_text_json_smile_yaml_or_cbor

**Comment by nz** [comment]
Thanks Matthew, nice catch! It looks like we're currently relying on the `Content-type: application/json` header, which is no longer respected for this purpose, in favor of the `Accept` header or the query string parameter. I'll go ahead and get this fixed up in a jiffy.

**Comment by matthewdu** [comment]
Yup, `Accept` header is even better.
