### ISSUE TITLE
Do not print elasticsearch_url

### ISSUE THREAD

**Issue by alranel** [omc/searchyll#37]
As of now, the full URL is printed to console:

https://github.com/omc/searchyll/blob/110bb95f5ef77e37ed1af73172bf386be55d39b4/lib/searchyll.rb#L12-L15

However, if the URL contains authentication credentials (e.g. `https://user:pass@host`) and we're running in a CI/CD enrivonment, such credentials get exposed in the build logs.
I propose to avoid printing the full URL, or only print it when running with the jekyll `--verbose` option.

**Comment by allizad** [comment]
Yep, good call — this should be removed. I'm against printing it even with a verbose option. Feel free to open a PR to remove the url interpolation - I'll merge it - otherwise it will be fixed in future PR's.

**Comment by alranel** [comment]
PR submitted! Thank you :)
