### ISSUE TITLE
[ping] Is Searchyll still maintained?

### ISSUE THREAD

**Issue by bfabio** [omc/searchyll#51]
Hello @allizad @nz @robsears @drusellers, thanks for Searchyll it's a really cool project and we use it on https://developers.italia.it.

We noticed it's not getting commits lately, so I'd like to ask if you're still maintaining it and what's the status of the project in general.

**Comment by drusellers** [comment]
@bfabio it's still used internally, for our purposes I consider it done. But we are always happy to receive pull requests or ideas. :)

**Comment by bfabio** [comment]
@drusellers Thanks, glad to hear that!
